// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for MainNavigation documents */
interface MainNavigationDocumentData {
    /**
     * Navigacija field in *MainNavigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: main_navigation.nav[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    nav: prismicT.GroupField<Simplify<MainNavigationDocumentDataNavItem>>;
}
/**
 * Item in MainNavigation → Navigacija
 *
 */
export interface MainNavigationDocumentDataNavItem {
    /**
     * Naslov field in *MainNavigation → Navigacija*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Naslov
     * - **API ID Path**: main_navigation.nav[].naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    naslov: prismicT.KeyTextField;
    /**
     * Link field in *MainNavigation → Navigacija*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: main_navigation.nav[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.RelationField;
}
/**
 * MainNavigation document from Prismic
 *
 * - **API ID**: `main_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainNavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MainNavigationDocumentData>, "main_navigation", Lang>;
/** Content for Naslovna documents */
interface NaslovnaDocumentData {
    /**
     * Slice Zone field in *Naslovna*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: naslovna.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NaslovnaDocumentDataSlicesSlice>;
    /**
     * Naslov strane field in *Naslovna*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Naslov strane
     * - **API ID Path**: naslovna.page_title
     * - **Tab**: Meta Data
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * Ključne reči (razdvojene zarezom) field in *Naslovna*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Ključne reči
     * - **API ID Path**: naslovna.meta_keywords
     * - **Tab**: Meta Data
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_keywords: prismicT.KeyTextField;
    /**
     * Tekst ukratko (1 pasus ili 2-3 rečenice) field in *Naslovna*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Tekst ukratko
     * - **API ID Path**: naslovna.meta_description
     * - **Tab**: Meta Data
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * Slika strane field in *Naslovna*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: naslovna.meta_image
     * - **Tab**: Meta Data
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismicT.ImageField<never>;
}
/**
 * Slice for *Naslovna → Slice Zone*
 *
 */
type NaslovnaDocumentDataSlicesSlice = SliderSlice | Banner1Slice | BannerTriptihSlice | Banner2Slice;
/**
 * Naslovna document from Prismic
 *
 * - **API ID**: `naslovna`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NaslovnaDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<NaslovnaDocumentData>, "naslovna", Lang>;
/** Content for Strana documents */
interface StranaDocumentData {
    /**
     * Naslov field in *Strana*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Naslov
     * - **API ID Path**: strana.naslov
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.RichTextField;
    /**
     * Slika za uzglavlje field in *Strana*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: strana.slika_uzglavlje
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika_uzglavlje: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Strana*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: strana.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<StranaDocumentDataSlicesSlice>;
    /**
     * Naslov strane field in *Strana*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Naslov strane
     * - **API ID Path**: strana.page_title
     * - **Tab**: Meta Data
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_title: prismicT.KeyTextField;
    /**
     * Ključne reči (razdvojene zarezom) field in *Strana*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Ključne reči
     * - **API ID Path**: strana.meta_keywords
     * - **Tab**: Meta Data
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_keywords: prismicT.KeyTextField;
    /**
     * Tekst ukratko (1 pasus ili 2-3 rečenice) field in *Strana*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Tekst ukratko
     * - **API ID Path**: strana.meta_description
     * - **Tab**: Meta Data
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * Slika strane field in *Strana*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: strana.meta_image
     * - **Tab**: Meta Data
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismicT.ImageField<never>;
}
/**
 * Slice for *Strana → Slice Zone*
 *
 */
type StranaDocumentDataSlicesSlice = Banner1Slice | TekstSlice | StanoviSlice | SlikaSlice | MaterijaliSlice | ProjektiSlice | FotoGalerijaSlice | KontaktFormaSlice;
/**
 * Strana document from Prismic
 *
 * - **API ID**: `strana`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StranaDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<StranaDocumentData>, "strana", Lang>;
export type AllDocumentTypes = MainNavigationDocument | NaslovnaDocument | StranaDocument;
/**
 * Primary content in Banner1 → Primary
 *
 */
interface Banner1SliceDefaultPrimary {
    /**
     * Podnaslov field in *Banner1 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Podnaslov
     * - **API ID Path**: banner1.primary.podnaslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    podnaslov: prismicT.KeyTextField;
    /**
     * Naslov field in *Banner1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Naslov
     * - **API ID Path**: banner1.primary.naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.TitleField;
    /**
     * Tekst field in *Banner1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Tekst
     * - **API ID Path**: banner1.primary.tekst
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tekst: prismicT.RichTextField;
    /**
     * Link field in *Banner1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Upišite i linkujte tekst
     * - **API ID Path**: banner1.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link: prismicT.RichTextField;
    /**
     * Slika field in *Banner1 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner1.primary.slika
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika: prismicT.ImageField<never>;
    /**
     * Boja pozadine field in *Banner1 → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: Izaberite boju pozadine banera
     * - **API ID Path**: banner1.primary.boja
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    boja: prismicT.ColorField;
}
/**
 * Default variation for Banner1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Banner1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Banner1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Banner1SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Banner1*
 *
 */
type Banner1SliceVariation = Banner1SliceDefault;
/**
 * Banner1 Shared Slice
 *
 * - **API ID**: `banner1`
 * - **Description**: `Banner1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Banner1Slice = prismicT.SharedSlice<"banner1", Banner1SliceVariation>;
/**
 * Primary content in Banner2 → Primary
 *
 */
interface Banner2SliceDefaultPrimary {
    /**
     * Naslov field in *Banner2 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Naslov
     * - **API ID Path**: banner2.primary.naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.RichTextField;
    /**
     * Tekst field in *Banner2 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Tekst
     * - **API ID Path**: banner2.primary.tekst
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tekst: prismicT.RichTextField;
    /**
     * Link field in *Banner2 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Upišite i linkujte tekst
     * - **API ID Path**: banner2.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link: prismicT.RichTextField;
    /**
     * Slika za pozadinu field in *Banner2 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner2.primary.slika
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika: prismicT.ImageField<never>;
    /**
     * Boja pozadine field in *Banner2 → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: Izaberite boju pozadine banera
     * - **API ID Path**: banner2.primary.boja
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    boja: prismicT.ColorField;
}
/**
 * Default variation for Banner2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Banner2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Banner2SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Banner2SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Banner2*
 *
 */
type Banner2SliceVariation = Banner2SliceDefault;
/**
 * Banner2 Shared Slice
 *
 * - **API ID**: `banner2`
 * - **Description**: `Banner2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Banner2Slice = prismicT.SharedSlice<"banner2", Banner2SliceVariation>;
/**
 * Item in BannerTriptih → Items
 *
 */
export interface BannerTriptihSliceDefaultItem {
    /**
     * Slika field in *BannerTriptih → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_triptih.items[].slika
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika: prismicT.ImageField<never>;
    /**
     * Naslov field in *BannerTriptih → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Naslov
     * - **API ID Path**: banner_triptih.items[].naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.TitleField;
    /**
     * Link field in *BannerTriptih → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_triptih.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.RelationField<"strana">;
    /**
     * Ikonica field in *BannerTriptih → Items*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: Ikonica pored naslova
     * - **API ID Path**: banner_triptih.items[].ikonica
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    ikonica: prismicT.LinkToMediaField;
}
/**
 * Default variation for BannerTriptih Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BannerTriptih`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerTriptihSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<BannerTriptihSliceDefaultItem>>;
/**
 * Slice variation for *BannerTriptih*
 *
 */
type BannerTriptihSliceVariation = BannerTriptihSliceDefault;
/**
 * BannerTriptih Shared Slice
 *
 * - **API ID**: `banner_triptih`
 * - **Description**: `BannerTriptih`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerTriptihSlice = prismicT.SharedSlice<"banner_triptih", BannerTriptihSliceVariation>;
/**
 * Item in FotoGalerija → Items
 *
 */
export interface FotoGalerijaSliceDefaultItem {
    /**
     * Slika field in *FotoGalerija → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: foto_galerija.items[].slika
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika: prismicT.ImageField<"thumbnail" | "medium">;
}
/**
 * Default variation for FotoGalerija Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FotoGalerija`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FotoGalerijaSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<FotoGalerijaSliceDefaultItem>>;
/**
 * Slice variation for *FotoGalerija*
 *
 */
type FotoGalerijaSliceVariation = FotoGalerijaSliceDefault;
/**
 * FotoGalerija Shared Slice
 *
 * - **API ID**: `foto_galerija`
 * - **Description**: `FotoGalerija`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FotoGalerijaSlice = prismicT.SharedSlice<"foto_galerija", FotoGalerijaSliceVariation>;
/**
 * Primary content in KontaktBanner → Primary
 *
 */
interface KontaktBannerSliceDefaultPrimary {
    /**
     * Adresa ikonica field in *KontaktBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: kontakt_banner.primary.adresa_ikonica
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    adresa_ikonica: prismicT.ImageField<never>;
    /**
     * Adresa field in *KontaktBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Adresa
     * - **API ID Path**: kontakt_banner.primary.adresa
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    adresa: prismicT.RichTextField;
    /**
     * Telefon ikonica field in *KontaktBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: kontakt_banner.primary.telefon_ikonica
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    telefon_ikonica: prismicT.ImageField<never>;
    /**
     * Telefoni field in *KontaktBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Telefoni
     * - **API ID Path**: kontakt_banner.primary.telefoni
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    telefoni: prismicT.RichTextField;
    /**
     * E-mail ikonica field in *KontaktBanner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: kontakt_banner.primary.e_mail_ikonica
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    e_mail_ikonica: prismicT.ImageField<never>;
    /**
     * E-mail field in *KontaktBanner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: E-mail
     * - **API ID Path**: kontakt_banner.primary.e_mail
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    e_mail: prismicT.RichTextField;
}
/**
 * Default variation for KontaktBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `KontaktBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type KontaktBannerSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<KontaktBannerSliceDefaultPrimary>, never>;
/**
 * Slice variation for *KontaktBanner*
 *
 */
type KontaktBannerSliceVariation = KontaktBannerSliceDefault;
/**
 * KontaktBanner Shared Slice
 *
 * - **API ID**: `kontakt_banner`
 * - **Description**: `KontaktBanner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type KontaktBannerSlice = prismicT.SharedSlice<"kontakt_banner", KontaktBannerSliceVariation>;
/**
 * Primary content in KontaktForma → Primary
 *
 */
interface KontaktFormaSliceDefaultPrimary {
    /**
     * Naslov field in *KontaktForma → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Naslov
     * - **API ID Path**: kontakt_forma.primary.naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.RichTextField;
}
/**
 * Default variation for KontaktForma Slice
 *
 * - **API ID**: `default`
 * - **Description**: `KontaktForma`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type KontaktFormaSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<KontaktFormaSliceDefaultPrimary>, never>;
/**
 * Slice variation for *KontaktForma*
 *
 */
type KontaktFormaSliceVariation = KontaktFormaSliceDefault;
/**
 * KontaktForma Shared Slice
 *
 * - **API ID**: `kontakt_forma`
 * - **Description**: `KontaktForma`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type KontaktFormaSlice = prismicT.SharedSlice<"kontakt_forma", KontaktFormaSliceVariation>;
/**
 * Primary content in Materijali → Primary
 *
 */
interface MaterijaliSliceDefaultPrimary {
    /**
     * Podnaslov field in *Materijali → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Podnaslov
     * - **API ID Path**: materijali.primary.podnaslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    podnaslov: prismicT.KeyTextField;
    /**
     * Naslov field in *Materijali → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Naslov
     * - **API ID Path**: materijali.primary.naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.TitleField;
    /**
     * Opis field in *Materijali → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Opis
     * - **API ID Path**: materijali.primary.opis
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    opis: prismicT.RichTextField;
}
/**
 * Item in Materijali → Items
 *
 */
export interface MaterijaliSliceDefaultItem {
    /**
     * Slike field in *Materijali → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: materijali.items[].slike
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slike: prismicT.ImageField<never>;
}
/**
 * Default variation for Materijali Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Materijali`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MaterijaliSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MaterijaliSliceDefaultPrimary>, Simplify<MaterijaliSliceDefaultItem>>;
/**
 * Slice variation for *Materijali*
 *
 */
type MaterijaliSliceVariation = MaterijaliSliceDefault;
/**
 * Materijali Shared Slice
 *
 * - **API ID**: `materijali`
 * - **Description**: `Materijali`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MaterijaliSlice = prismicT.SharedSlice<"materijali", MaterijaliSliceVariation>;
/**
 * Primary content in Projekti → Primary
 *
 */
interface ProjektiSliceDefaultPrimary {
    /**
     * Podnaslov field in *Projekti → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Podnaslov
     * - **API ID Path**: projekti.primary.podnaslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    podnaslov: prismicT.KeyTextField;
    /**
     * Naslov field in *Projekti → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Naslov / Naziv projekta
     * - **API ID Path**: projekti.primary.naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.TitleField;
    /**
     * Datum realizacije field in *Projekti → Primary*
     *
     * - **Field Type**: Date
     * - **Placeholder**: Datum realizacije projekta
     * - **API ID Path**: projekti.primary.datum
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    datum: prismicT.DateField;
    /**
     * Opis field in *Projekti → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Opis
     * - **API ID Path**: projekti.primary.opis
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    opis: prismicT.RichTextField;
}
/**
 * Item in Projekti → Items
 *
 */
export interface ProjektiSliceDefaultItem {
    /**
     * Slike field in *Projekti → Items*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: Slike projekta
     * - **API ID Path**: projekti.items[].slike
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    slike: prismicT.LinkToMediaField;
}
/**
 * Default variation for Projekti Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Projekti`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjektiSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjektiSliceDefaultPrimary>, Simplify<ProjektiSliceDefaultItem>>;
/**
 * Slice variation for *Projekti*
 *
 */
type ProjektiSliceVariation = ProjektiSliceDefault;
/**
 * Projekti Shared Slice
 *
 * - **API ID**: `projekti`
 * - **Description**: `Projekti`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjektiSlice = prismicT.SharedSlice<"projekti", ProjektiSliceVariation>;
/**
 * Item in Slider → Items
 *
 */
export interface SliderSliceDefaultItem {
    /**
     * Podnaslov field in *Slider → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Podnaslov
     * - **API ID Path**: slider.items[].podnaslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    podnaslov: prismicT.KeyTextField;
    /**
     * Naslov field in *Slider → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Naslov
     * - **API ID Path**: slider.items[].naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.RichTextField;
    /**
     * Opis field in *Slider → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Opis
     * - **API ID Path**: slider.items[].opis
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    opis: prismicT.RichTextField;
    /**
     * Slika field in *Slider → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: slider.items[].slika
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika: prismicT.ImageField<never>;
    /**
     * Dugme Tekst field in *Slider → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Dugme Tekst
     * - **API ID Path**: slider.items[].dugme_tekst
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    dugme_tekst: prismicT.KeyTextField;
    /**
     * Link field in *Slider → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Izaberite link
     * - **API ID Path**: slider.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Slider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SliderSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<SliderSliceDefaultItem>>;
/**
 * Slice variation for *Slider*
 *
 */
type SliderSliceVariation = SliderSliceDefault;
/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: `Slider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SliderSlice = prismicT.SharedSlice<"slider", SliderSliceVariation>;
/**
 * Primary content in Slika → Primary
 *
 */
interface SlikaSliceDefaultPrimary {
    /**
     * Slika field in *Slika → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: slika.primary.slika
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika: prismicT.ImageField<never>;
}
/**
 * Default variation for Slika Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Slika`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SlikaSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SlikaSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Slika*
 *
 */
type SlikaSliceVariation = SlikaSliceDefault;
/**
 * Slika Shared Slice
 *
 * - **API ID**: `slika`
 * - **Description**: `Slika`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SlikaSlice = prismicT.SharedSlice<"slika", SlikaSliceVariation>;
/**
 * Primary content in Stanovi → Primary
 *
 */
interface StanoviSliceDefaultPrimary {
    /**
     * Naslov field in *Stanovi → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Naslov
     * - **API ID Path**: stanovi.primary.naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.TitleField;
    /**
     * Opis field in *Stanovi → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Opis
     * - **API ID Path**: stanovi.primary.opis
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    opis: prismicT.RichTextField;
}
/**
 * Item in Stanovi → Items
 *
 */
export interface StanoviSliceDefaultItem {
    /**
     * Slika field in *Stanovi → Items*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: Slika
     * - **API ID Path**: stanovi.items[].slika
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    slika: prismicT.LinkToMediaField;
}
/**
 * Default variation for Stanovi Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Stanovi`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StanoviSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<StanoviSliceDefaultPrimary>, Simplify<StanoviSliceDefaultItem>>;
/**
 * Slice variation for *Stanovi*
 *
 */
type StanoviSliceVariation = StanoviSliceDefault;
/**
 * Stanovi Shared Slice
 *
 * - **API ID**: `stanovi`
 * - **Description**: `Stanovi`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StanoviSlice = prismicT.SharedSlice<"stanovi", StanoviSliceVariation>;
/**
 * Item in Tekst → Items
 *
 */
export interface TekstSliceDefaultItem {
    /**
     * Sadržaj field in *Tekst → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Sadržaj
     * - **API ID Path**: tekst.items[].sadrzaj
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    sadrzaj: prismicT.RichTextField;
}
/**
 * Default variation for Tekst Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Tekst`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TekstSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<TekstSliceDefaultItem>>;
/**
 * Primary content in Tekst → Primary
 *
 */
interface TekstSliceTekstSaSlikomPrimary {
    /**
     * Naslov field in *Tekst → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Naslov
     * - **API ID Path**: tekst.primary.naslov
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    naslov: prismicT.RichTextField;
    /**
     * Slika za uzglavlje field in *Tekst → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: tekst.primary.slika_uzglavlje
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika_uzglavlje: prismicT.ImageField<never>;
}
/**
 * Item in Tekst → Items
 *
 */
export interface TekstSliceTekstSaSlikomItem {
    /**
     * Sadržaj field in *Tekst → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Sadržaj
     * - **API ID Path**: tekst.items[].sadrzaj
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    sadrzaj: prismicT.RichTextField;
    /**
     * Slika field in *Tekst → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: tekst.items[].slika
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slika: prismicT.ImageField<never>;
}
/**
 * Tekst sa slikom variation for Tekst Slice
 *
 * - **API ID**: `tekstSaSlikom`
 * - **Description**: `Tekst`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TekstSliceTekstSaSlikom = prismicT.SharedSliceVariation<"tekstSaSlikom", Simplify<TekstSliceTekstSaSlikomPrimary>, Simplify<TekstSliceTekstSaSlikomItem>>;
/**
 * Slice variation for *Tekst*
 *
 */
type TekstSliceVariation = TekstSliceDefault | TekstSliceTekstSaSlikom;
/**
 * Tekst Shared Slice
 *
 * - **API ID**: `tekst`
 * - **Description**: `Tekst`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TekstSlice = prismicT.SharedSlice<"tekst", TekstSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { MainNavigationDocumentData, MainNavigationDocumentDataNavItem, MainNavigationDocument, NaslovnaDocumentData, NaslovnaDocumentDataSlicesSlice, NaslovnaDocument, StranaDocumentData, StranaDocumentDataSlicesSlice, StranaDocument, AllDocumentTypes, Banner1SliceDefaultPrimary, Banner1SliceDefault, Banner1SliceVariation, Banner1Slice, Banner2SliceDefaultPrimary, Banner2SliceDefault, Banner2SliceVariation, Banner2Slice, BannerTriptihSliceDefaultItem, BannerTriptihSliceDefault, BannerTriptihSliceVariation, BannerTriptihSlice, FotoGalerijaSliceDefaultItem, FotoGalerijaSliceDefault, FotoGalerijaSliceVariation, FotoGalerijaSlice, KontaktBannerSliceDefaultPrimary, KontaktBannerSliceDefault, KontaktBannerSliceVariation, KontaktBannerSlice, KontaktFormaSliceDefaultPrimary, KontaktFormaSliceDefault, KontaktFormaSliceVariation, KontaktFormaSlice, MaterijaliSliceDefaultPrimary, MaterijaliSliceDefaultItem, MaterijaliSliceDefault, MaterijaliSliceVariation, MaterijaliSlice, ProjektiSliceDefaultPrimary, ProjektiSliceDefaultItem, ProjektiSliceDefault, ProjektiSliceVariation, ProjektiSlice, SliderSliceDefaultItem, SliderSliceDefault, SliderSliceVariation, SliderSlice, SlikaSliceDefaultPrimary, SlikaSliceDefault, SlikaSliceVariation, SlikaSlice, StanoviSliceDefaultPrimary, StanoviSliceDefaultItem, StanoviSliceDefault, StanoviSliceVariation, StanoviSlice, TekstSliceDefaultItem, TekstSliceDefault, TekstSliceTekstSaSlikomPrimary, TekstSliceTekstSaSlikomItem, TekstSliceTekstSaSlikom, TekstSliceVariation, TekstSlice };
    }
}
